### ISSUE TITLE
Native Hipchat API support

### ISSUE THREAD

**Issue by CVTJNII** [litaio/lita-hipchat#42]
Looking at this adapter it appears to be XMPP based on the gemspec and connector.rb.  I'd prefer to use Hipchat's API for new integration for both licensing and to allow smoother integration.  Is there a plan to move from xmpp to something like the hipchat gem?

**Comment by jimmycuadra** [comment]
No, not currently. If you want to develop it as a separate adapter, I'm sure there would be other people interested!

**Comment by CVTJNII** [comment]
Fair enough, thanks!
