### ISSUE TITLE
Make bot wait for input "wait for chat route trigger"

### ISSUE THREAD

**Issue by asser-hassan** [litaio/lita-hipchat#45]
Is there a way to make lita wait for input (e.g: yes/no) before proceeding to the next iteration of a process?

**Comment by jimmycuadra** [comment]
Can you clarify what you mean by "next iteration of a process?"

**Comment by asser-hassan** [comment]
As an example: one of my bots polls open incidents and performs business logic to formulate the next automated action, then prods the user for confirmation.
Ideally I'd like the bot to be able to "send confirmation message", then treat the next message in the room as a response.
I guess I can do that with a chat route, but if there's an intrinsic variable for this it would be great.
Apologies if it's still not clear enough.

**Comment by jimmycuadra** [comment]
You can use [lita-confirmation](https://github.com/jimmycuadra/lita-confirmation) as a generic mechanism for requiring a user to confirm a command before it's actually executed. Will that do what you want?

**Comment by asser-hassan** [comment]
Yeah I think that will work beautifully! 👍  Thanks and I apologize if the question was too basic
